spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shoppingmall
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  main:
    allow-bean-definition-overriding: true

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    root: info
    com.example.shoppingmall: info
    #org.springframework.security: debug

jwt:
  secret: secretKey2G312A3E224A78H51R6dfvnjhgSf3asD3N5KE23LaeE
  tokenValidTime: 3600000 # 1시간

upload:
  path: "/Users/zhscl/Desktop/git/ShoppingmallProject/ShoppingmallProject/src/main/resources/static/img"

iamport:
  imp_key: ${IAM_REST_API_KEY}
  imp_secret: ${IAM_SECRET_KEY}